/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;


import java.io.File;
import java.util.regex.*;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.Product;

/**
 *
 * @author DELL
 */
public class CreateJpanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJpanel
     */
    Product product;
    
    public CreateJpanel(Product product) {
        initComponents();
        this.product = product;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        txtdob = new javax.swing.JTextField();
        lbltelephone = new javax.swing.JLabel();
        lbldob = new javax.swing.JLabel();
        txttelephone = new javax.swing.JTextField();
        lblemail = new javax.swing.JLabel();
        txtfax = new javax.swing.JTextField();
        lblfax = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        lblmedNo = new javax.swing.JLabel();
        txtssn = new javax.swing.JTextField();
        lblssn = new javax.swing.JLabel();
        txtmedNo = new javax.swing.JTextField();
        lblbankNo = new javax.swing.JLabel();
        txthealthNo = new javax.swing.JTextField();
        lblhealthNo = new javax.swing.JLabel();
        txtbankNo = new javax.swing.JTextField();
        lblvehicleNo = new javax.swing.JLabel();
        txtlicenseNo = new javax.swing.JTextField();
        lbllicenseNo = new javax.swing.JLabel();
        txtvehicleNo = new javax.swing.JTextField();
        lbllinkedIn = new javax.swing.JLabel();
        txtdeviceNo = new javax.swing.JTextField();
        lbldeviceNo = new javax.swing.JLabel();
        txtlinkedIn = new javax.swing.JTextField();
        lblbiometric = new javax.swing.JLabel();
        txtipAddress = new javax.swing.JTextField();
        lblipAddress = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        nlbl = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        invName = new javax.swing.JLabel();
        invTele = new javax.swing.JLabel();
        invEmail = new javax.swing.JLabel();
        invSsn = new javax.swing.JLabel();
        uploadImage = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CREATE PROFILE");

        lblAddress.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblAddress.setText("Address :");

        txtName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNameFocusLost(evt);
            }
        });
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameKeyReleased(evt);
            }
        });

        lblName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblName.setText("Name :");

        lbltelephone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbltelephone.setText("Telephone No :");

        lbldob.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbldob.setText("Date of Birth :");

        txttelephone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txttelephoneFocusLost(evt);
            }
        });

        lblemail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblemail.setText("Email :");

        lblfax.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblfax.setText("Fax No :");

        txtemail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtemailFocusLost(evt);
            }
        });

        lblmedNo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblmedNo.setText("Medical Record No :");

        txtssn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtssnFocusLost(evt);
            }
        });

        lblssn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblssn.setText("SSN :");

        lblbankNo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblbankNo.setText("Bank Account No :");

        lblhealthNo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblhealthNo.setText("Health  Benificiary No :");

        lblvehicleNo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblvehicleNo.setText("Vehicle No :");

        lbllicenseNo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbllicenseNo.setText("License No :");

        lbllinkedIn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbllinkedIn.setText("LinkedIn :");

        lbldeviceNo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbldeviceNo.setText("Device No :");

        lblbiometric.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblbiometric.setText("Photo :");

        lblipAddress.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblipAddress.setText("IP Address :");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        invName.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        invName.setForeground(new java.awt.Color(204, 0, 0));

        invTele.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        invTele.setForeground(new java.awt.Color(204, 0, 0));

        invEmail.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        invEmail.setForeground(new java.awt.Color(204, 0, 0));

        invSsn.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        invSsn.setForeground(new java.awt.Color(204, 0, 0));

        uploadImage.setText("Upload");
        uploadImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadImageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblipAddress)
                                .addComponent(lblbiometric))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(38, 38, 38)
                                    .addComponent(txtipAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(84, 84, 84)
                                    .addComponent(uploadImage, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(172, 172, 172))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbldeviceNo)
                                .addComponent(lbllinkedIn))
                            .addGap(38, 38, 38)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtdeviceNo, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtlinkedIn, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbllicenseNo)
                                .addComponent(lblvehicleNo))
                            .addGap(38, 38, 38)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtlicenseNo, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                                .addComponent(txtvehicleNo))
                            .addGap(172, 172, 172))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblssn)
                                .addComponent(lblmedNo))
                            .addGap(38, 38, 38)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtssn, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                                .addComponent(txtmedNo))
                            .addGap(18, 18, 18)
                            .addComponent(invSsn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(98, 98, 98))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblemail)
                                .addComponent(lblfax))
                            .addGap(38, 38, 38)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtemail, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                                .addComponent(txtfax))
                            .addGap(18, 18, 18)
                            .addComponent(invEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(98, 98, 98))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbldob)
                                .addComponent(lbltelephone))
                            .addGap(38, 38, 38)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txttelephone, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                                .addComponent(txtdob))
                            .addGap(18, 18, 18)
                            .addComponent(invTele, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(77, 77, 77))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblName)
                                .addComponent(lblAddress))
                            .addGap(38, 38, 38)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(29, 29, 29)
                                    .addComponent(invName, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(nlbl))))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblhealthNo)
                                .addComponent(lblbankNo))
                            .addGap(38, 38, 38)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txthealthNo, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtbankNo, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(172, 172, 172)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(btnSave)))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nlbl)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblName)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(invName)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldob)
                    .addComponent(txtdob, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(invTele))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfax, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblfax, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblemail, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(invEmail))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblssn)
                    .addComponent(txtssn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(invSsn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmedNo, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmedNo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblhealthNo)
                    .addComponent(txthealthNo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblbankNo, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtbankNo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbllicenseNo)
                    .addComponent(txtlicenseNo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblvehicleNo, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtvehicleNo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtdeviceNo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbldeviceNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbllinkedIn, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtlinkedIn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblipAddress)
                    .addComponent(txtipAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblbiometric, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uploadImage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        boolean check;
        String alphapattern = "^[a-zA-Z]{1,}$";
        String emailpattern = "^[a-zA-Z0-9+_.-]+@[a-zA-Z0-9.-]+$";
        String numpattern = "(0|91)?[7-9][0-9]{9}";
        String ssnpattern = "^(?!666|000|9\\d{2})\\d{3}"
                       + "-(?!00)\\d{2}-"
                       +"(?!0{4})\\d{4}$";
        
        Pattern aP = Pattern.compile(alphapattern);
        Pattern eP = Pattern.compile(emailpattern);
        Pattern nP = Pattern.compile(numpattern);
        Pattern sP = Pattern.compile(ssnpattern);
        
        Matcher aM = aP.matcher(txtName.getText());
        Matcher eM = eP.matcher(txtemail.getText());
        Matcher nM = nP.matcher(txttelephone.getText());
        Matcher sM = sP.matcher(txtssn.getText());
       
                
                
        if ((!eM.matches()) || (!aM.matches()) || (!nM.matches()) || (!sM.matches()) )
            {
            check=false;
            }
        else{
                check=true;
            }
        
        
        
        if (check == true){
            product.setAddress(txtAddress.getText());
            product.setName(txtName.getText());
            product.setDob(txtdob.getText());
            product.setBankNo(Long.parseLong(txtbankNo.getText()));
            product.setDeviceNo(Long.parseLong(txtdeviceNo.getText()));
            product.setEmail(txtemail.getText());
            product.setFax(Long.parseLong(txtfax.getText()));
            product.setHealthNo(Long.parseLong(txthealthNo.getText()));
            product.setIpAddress(txtipAddress.getText());
            product.setLicenseNo(Long.parseLong(txtlicenseNo.getText()));
            product.setLinkedIn(txtlinkedIn.getText());
            product.setMedNo(Long.parseLong(txtmedNo.getText()));
            product.setSsn(txtssn.getText());
            product.setTelephone(Long.parseLong(txttelephone.getText()));
            product.setVehicleNo(txtvehicleNo.getText());
            JOptionPane.showMessageDialog(this, "Profile Created Successfully !");}
        
        else {
            JOptionPane.showMessageDialog(this, "Profile cannot Be Created.");}
        
        
        
        
        
    
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyReleased
       
       
    }//GEN-LAST:event_txtNameKeyReleased

    private void txtNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusLost
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z]{1,}$";
        Pattern Patt = Pattern.compile(PATTERN);
        Matcher match = Patt.matcher(txtName.getText());
        if (!match.matches()){
            invName.setText("Invalid !");
            }
        else {
              invName.setText(null);
            }
        
      
        
    }//GEN-LAST:event_txtNameFocusLost

    private void txttelephoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txttelephoneFocusLost
        // TODO add your handling code here:
        String PATTERN = "(0|91)?[7-9][0-9]{9}";
        Pattern Patt = Pattern.compile(PATTERN);
        Matcher match = Patt.matcher(txttelephone.getText());
        if (!match.matches()){
            invTele.setText("Invalid !");
            }
        else {
              invTele.setText(null);
            }
        
        
    }//GEN-LAST:event_txttelephoneFocusLost

    private void txtemailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtemailFocusLost
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z0-9+_.-]+@[a-zA-Z0-9.-]+$";
        Pattern Patt = Pattern.compile(PATTERN);
        Matcher match = Patt.matcher(txtemail.getText());
        if (!match.matches()){
            invEmail.setText("Invalid !");
            }
        else {
              invEmail.setText(null);
        
    }//GEN-LAST:event_txtemailFocusLost
    }
    private void txtssnFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtssnFocusLost
        // TODO add your handling code here:
        String PATTERN = "^(?!666|000|9\\d{2})\\d{3}"
                       + "-(?!00)\\d{2}-"
                       +"(?!0{4})\\d{4}$";
        Pattern Patt = Pattern.compile(PATTERN);
        Matcher match = Patt.matcher(txtssn.getText());
        if (!match.matches()){
            invSsn.setText("Invalid !");
            }
        else {
              invSsn.setText(null);
        
    }             
    }//GEN-LAST:event_txtssnFocusLost

    private void uploadImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadImageActionPerformed
        // TODO add your handling code here:
        JFileChooser imageFile = new JFileChooser();
        imageFile.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter f = new FileNameExtensionFilter("*.Images", "jpg","gif","png");
        imageFile.addChoosableFileFilter(f);
        int sav = imageFile.showSaveDialog(null);
        if(sav == JFileChooser.APPROVE_OPTION)
            {
                File selectedimageFile = imageFile.getSelectedFile();
                upload(selectedimageFile);
            }
        else if(sav == JFileChooser.CANCEL_OPTION)
        {
            JOptionPane.showMessageDialog(this, "File not selected");
        }
        
    }//GEN-LAST:event_uploadImageActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel invEmail;
    private javax.swing.JLabel invName;
    private javax.swing.JLabel invSsn;
    private javax.swing.JLabel invTele;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblbankNo;
    private javax.swing.JLabel lblbiometric;
    private javax.swing.JLabel lbldeviceNo;
    private javax.swing.JLabel lbldob;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblfax;
    private javax.swing.JLabel lblhealthNo;
    private javax.swing.JLabel lblipAddress;
    private javax.swing.JLabel lbllicenseNo;
    private javax.swing.JLabel lbllinkedIn;
    private javax.swing.JLabel lblmedNo;
    private javax.swing.JLabel lblssn;
    private javax.swing.JLabel lbltelephone;
    private javax.swing.JLabel lblvehicleNo;
    private javax.swing.JLabel nlbl;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtbankNo;
    private javax.swing.JTextField txtdeviceNo;
    private javax.swing.JTextField txtdob;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfax;
    private javax.swing.JTextField txthealthNo;
    private javax.swing.JTextField txtipAddress;
    private javax.swing.JTextField txtlicenseNo;
    private javax.swing.JTextField txtlinkedIn;
    private javax.swing.JTextField txtmedNo;
    private javax.swing.JTextField txtssn;
    private javax.swing.JTextField txttelephone;
    private javax.swing.JTextField txtvehicleNo;
    private javax.swing.JButton uploadImage;
    // End of variables declaration//GEN-END:variables
}
